### ISSUE TITLE
Expose allow-listed Prometheus metrics to end-users

### ISSUE THREAD

**Issue by vlerenc** [gardener/monitoring#3]
End users would benefit from direct access to Prometheus, but we were always reluctant to just open up Prometheus as it also holds "implementation-detail" metrics that end users shouldn't be concerned with (e.g. in relation to internal control plane components that no end user directly interacts with).

According to @wyb1, we have the following options:
1. Expose just allow-listed metrics via proxy: This would have the disadvantages of manually maintaining the allow list and that it wouldn't include Prometheus itself, just the metrics via a proxy.
2. Set up another (end-user) Prometheus scrapping our (main) Prometheus: This would have the disadvantages of manually maintaining the allow list and setting up (TCD) and operating (TCO) another Prometheus instance.
3. Just open up our (main) Prometheus behind a feature gate: This would have the disadvantage, once the feature gate is opened, that all metrics would be exposed.

**Comment by wyb1** [comment]
Discussion to open up prometheus entirely: https://github.com/gardener/gardener/issues/4800

**Comment by vicwicker** [comment]
It is possible to access the shoot Prometheus by shoot owners since:

- https://github.com/gardener/gardener/pull/7007
